# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/media/arnav/905fa6d4-a08a-4e03-b964-5a9630b2702e/notes/src-tauri/migrations"
